<div id="banner">

   <a href="http://www.ruleml.org">
     <span id="logoimg"></span>
   </a>

   <h1><a href="http://2008.ruleml.org"><span
                  class="green">RuleML-2008</span></a></h1> 
  </div>

  <div id="bannertext">
   <p><span class="black">The International RuleML Symposium on Rule
   Interchange and Applications</span></p>
   <p><span class="green">Orlando, Florida: October 30-31, 2008</span></p>
  </div>

  <div id="navigation">
  <ul>
    <li> <a href="/index.php">HOME</a></li>
    <li> <a href="/objectives.php">ABOUT</a> </li>
    <li> <a href="/cfp.pdf">CALL FOR PAPERS</a> </li>
    <li> <a href="/sponsoring.php">SPONSORSHIP</a> </li>
    <li> <a href="/news.php" class="last">NEWS</a></li>
    <li> <a href="http://www.targetwire.com/vpo/rm/" >PRESS</a></li>
  </ul>
</div>
