  <div class="mainleft">

   <div class="title">Latest News</div>
   <div class="date" style="width: 80%;">Updated - November 12, 2008</div>
   <p><span style="font-weight: bold;">Presentation slides and photos from the symposium are on-line</span> <br />
      <a href="/news.php">read more news</a></p>

   <div class="title" style="margin-top: -2em;">The Symposium</div>
   <div class="navcontainer">
    <ul class="navlist">
    <li><a href="/attend.php">Who Will Attend</a></li>
    <li><a href="/highlights.php">Highlights</a></li>
    <li><a href="/keynotes.php">Keynote Speakers</a></li>
    <li><a href="/panel.php">Boxed Lunch Panel</a></li>
    <li><a href="/acceptedPapers.php">Accepted Papers</a></li>
     <li><a href="http://www.springer.com/computer/information+systems/book/978-3-540-88807-9">Proceedings</a></li>
   <li><a href="/program.php">Program</a></li>
    <li><a href="/registration.php">Registration</a></li>
    <li><a href="/venue.php">Venue</a></li>
    <li><a href="http://www.businessrulesforum.com/">Business Rule
    Forum</a></li>
    </ul>
   </div>

   <div class="title">Authors</div>
   <div class="navcontainer">
   <ul class="navlist">
<!--    <li class="active"><a href="#" id="current"></a></li> -->
    <li><a href="/objectives.php">Objectives</a></li>
    <li><a href="/topics.php">Topics</a></li>
    <li><a href="/challenge.php">RuleML-2008 Challenge</a></li>
    <li><a href="/submissions.php">Submission Guidelines</a></li>
    <li><a href="/cfp.pdf">Call for Papers (PDF)</a></li>
     <li><a href="/lightning.php">Other Calls</a></li>
   <li><a href="/dates.php">Important Dates</a></li>
   </ul>
   </div>

   <div class="title">Organisation</div>
   <div class="navcontainer">
    <ul class="navlist">
    <li><a href="/oc.php">Organising Committee</a></li>
    <li><a href="/pc.php">Program Committee</a></li>
    <li><a href="/sponsoring.php">Sponsorship</a></li>
    <li><a href="http://www.ruleml.org/RuleML-2008/RuleResponder/">
        Rule Responder Q&A</a></li>
    <li><a href="/promotion.php">Promotional Materials</a></li>
    <li><a href="/album/index.html">Photos</a></li>
    <li><a href="/RuleML-2008_Report.pdf">Report</a></li>
<!--
    <li><a href="/press.php">Press Corner</a></li>
-->
    </ul>
   </div>

   <div class="title">RuleML Initiative</div>
   <div class="navcontainer">
    <ul class="navlist">
    <li><a href="/about.php">About Us</a></li>
    <li><a href="/past.php">Past Events</a></li>
    </ul>
   </div>

   </div>

